# KerogsPHP Framework Configuration
# https://github.com/KSInfinite/KerogsPHP-Framework
# Thanks for using it.

# SEO Configuration
seo:
  title: "Quick Food Choice"
  title_short: "QFC"
  description: "Webapp-based order management application for restaurants. "
  keywords: "Web-based, Webapp, App, food, Quick FOOD Choice, order, management, application, restaurants."
  author: "Kerogs"
  lang: "English"
  lang_short: "en"
  color: "#a038ec"
  image: "https://raw.githubusercontent.com/KSInfinite/KerogsPHP-Framework/main/.ksinf/banner.png"
  favicon: "src/img/logo.png"
  sitemap: "src/xml/sitemap.xml"

# Labs/test IP authorization Configuration
labs:
  enable: false
  labsIPAuth:
    - 127.0.0.1

# Other
other:
  website_version: 1.0.0

framework:
  framework_version: 2.3.1-sh6
  title: "KerogsPHP Framework"
  title_short: "KsPHP Framework"